### ISSUE TITLE
Read this for better project management with github. It could be helpful.

### ISSUE THREAD

**Issue by ericchingalo** [udsm-programmers/IS282-2019#1]
Github offers a very nice feature called git flow, which enhences how we as developers can improve our way of doing a project with git. Click [here](https://datasift.github.io/gitflow/IntroducingGitFlow.html) for more information, and [here](https://danielkummer.github.io/git-flow-cheatsheet/) for a git flow cheat sheet.

**Comment by MAFTAH69** [comment]
Thanks,, But I don't think that we are all going to understand what the issue intended to deliver
